### ISSUE TITLE
Installation fails on OSX

### ISSUE THREAD

**Issue by techmaniack** [cloudreach/sceptre#107]
spectre installation fails on OSX

```
➜  play1 python -V
Python 2.7.13
➜  play1 pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
➜  play1 pip install spectre
Collecting spectre
  Could not find a version that satisfies the requirement spectre (from versions: )
No matching distribution found for spectre
```

**Comment by jamesroutley** [comment]
The tool is called sceptre, not spectre!

**Comment by techmaniack** [comment]
Oh god!
Will internet forget this?

**Comment by techmaniack** [comment]
So sceptre installation is giving an error too!

```
Installing collected packages: sceptre
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/sceptre'
```

**Comment by jamesroutley** [comment]
Are you using a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/)?

**Comment by techmaniack** [comment]
No.

**Comment by jamesroutley** [comment]
So sceptre works best when deployed in a virtualenv, that should solve the permission denied problem, but let me know if there are still issues

**Comment by techmaniack** [comment]
It works with venv.
