### ISSUE TITLE
Request Limit max retries exceeded

### ISSUE THREAD

**Issue by georgealton** [cloudreach/sceptre#149]
When deploying our environment we seem to hit the RetryLimitException, our environment is made of lots of modular cloud formation stacks, so a lot is going on. 

```
[2017-06-19 13:17:31] - sceptre.stack - 2017-06-19T12:17:27+00:00 region-1/bastion Bastion AWS::AutoScaling::AutoScalingGroup CREATE_IN_PROGRESS 
[2017-06-19 13:17:31] - sceptre.stack - 2017-06-19T12:17:28+00:00 region-1/bastion Bastion AWS::AutoScaling::AutoScalingGroup CREATE_IN_PROGRESS Resource creation Initiated
[2017-06-19 13:19:43] - sceptre.helpers - Request limit exceeded, pausing...
[2017-06-19 13:20:29] - sceptre.helpers - Request limit exceeded, pausing...
[2017-06-19 13:20:38] - sceptre.helpers - Request limit exceeded, pausing...
[2017-06-19 13:20:48] - sceptre.helpers - Request limit exceeded, pausing...
[2017-06-19 13:20:57] - sceptre.helpers - Request limit exceeded, pausing...
[2017-06-19 13:21:15] - sceptre.helpers - Request limit exceeded, pausing...
[2017-06-19 13:21:31] - sceptre.environment - Stack region-1/bastion failed to launch
Traceback (most recent call last):
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/environment.py", line 244, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/stack.py", line 274, in launch
    status = self.create()
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/stack.py", line 212, in create
    status = self._wait_for_completion()
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/stack.py", line 734, in _wait_for_completion
    status = self._get_simplified_status(self.get_status())
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/stack.py", line 638, in get_status
    status = self.describe()["Stacks"][0]["StackStatus"]
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/stack.py", line 379, in describe
    kwargs={"StackName": self.external_name}
  File "/Users/chrisf/git/dply/cloud-formation-templates/venv/lib/python2.7/site-packages/sceptre/helpers.py", line 52, in decorated
    "Exceeded request limit {0} times. Aborting.".format(max_retries)
RetryLimitExceededError: Exceeded request limit 5 times. Aborting.
```

Is there any recommendation here? Could `max_retries` be increased? or is there something that could be incorporated to decrease the polling frequency, to reduce the API overhead?

**Comment by jamesroutley** [comment]
Hey, yeah this is a known issue with the AWS APIs. We already catch `botocore.RateLimitExceeded` exceptions and retry the requests, with exponentially increasing delays. If the retry fails 5 times, we throw the `RetryLimitExceededError`, so Sceptre doesn't retry forever if e.g. the network connection fails. 

We'll bump the `max_retries` up to 30, which will hopefully fix this issue.

**Comment by jamesroutley** [comment]
v1.2.0
