### ISSUE TITLE
Can't call pdb in a hook due to module naming collision

### ISSUE THREAD

**Issue by akdor1154** [cloudreach/sceptre#245]
Let's say I'm writing a custom hook and I want to play around with the information provided to me by sceptre. The normal python way to do this might be:
```python
from sceptre.hooks import Hook
from pdb import set_trace

class CustomHook(Hook):
  def run(self):
    set_trace()
```

However, this causes a confusing traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sceptre/environment.py", line 247, in _manage_stack_build
    status = getattr(stack, command)()
  File "/usr/local/lib/python3.6/site-packages/sceptre/stack.py", line 274, in launch
    status = self.create()
  File "/usr/local/lib/python3.6/site-packages/sceptre/hooks/__init__.py", line 69, in decorated
    execute_hooks(self.hooks.get("before_" + func.__name__))
  File "/usr/local/lib/python3.6/site-packages/sceptre/hooks/__init__.py", line 57, in execute_hooks
    hook.run()
  File "/Users/jarrad/src/ow/sandpit/sceptre-playing/infra/hooks/custom.py", line 13, in run
    set_trace()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1585, in set_trace
    Pdb().set_trace(sys._getframe().f_back)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 143, in __init__
    cmd.Cmd.__init__(self, completekey, stdin, stdout)
  File "/usr/local/lib/python3.6/site-packages/sceptre/hooks/cmd.py", line 12, in __init__
    super(Cmd, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

On doing some reading, it looks like this is because sceptre's command hook module `cmd` conflicts with the builtin Python module `cmd`, which breaks `pdb`.
This pops up every so often in StackOverflow and GitHub issue pages in other Python projects; the general "solution" seems to be "don't name your modules `cmd.py`".
https://github.com/ParmEd/ParmEd/issues/148
https://github.com/google/python-fire/issues/19

**Comment by theseanything** [comment]
Yup, so this shouldn't be an issue come v2.0 - due this PR #205. The entry points import the cmd modules with an absolute path (`sceptre.hooks.cmd.Cmd`) and should conflict. Briefly tested and seems to work too..

**Comment by theseanything** [comment]
We could rename `cmd.py` to `command.py` as a patch for v1.x
