### ISSUE TITLE
AttributeError: 'Environment' object has no attribute 'stacks'

### ISSUE THREAD

**Issue by ThomLambert** [cloudreach/sceptre#247]
I had a flat environment config as shown below and everything was working nicely:
| config
| ____environment1
|   |____stack1.yaml
|   |____stack2.yaml

But then I have added a new directory inside environment1, and my config looked like the below tree:
| config
| ____environment1
|   |____stack1.yaml
|   |____stack2.yaml
|   |____subenvironment
|   |    |____stack3.yaml

From then, every sceptre command targeting stack1 or stack2 will crash with the below error (sceptre commands to stack3 are still working)

`Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre==1.3.0', 'console_scripts', 'sceptre')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/cli.py", line 96, in decorated
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/cli.py", line 494, in update_with_change_set
    with change_set(env.stacks[stack], change_set_name):
AttributeError: 'Environment' object has no attribute 'stacks'`

**Comment by theseanything** [comment]
Yup because of cascading stack configs - all environments need to be “leaf” environments (I.e. have no sub environments) for the stacks to be initialized. So in your second example ‘subenvironment’ is leaf environment, hence ‘stack3’ gets loaded. But ‘environment1’ is not because it contains ‘subenvironment’ which prevents  ‘stack1’ and ‘stack2’ from being loaded.

**Comment by ThomLambert** [comment]
Thanks for the analysis, will this be considered as normal behavior or as an issue?

**Comment by theseanything** [comment]
This is normal behavior for v1.x as we have cascading stack configs. For v2.0 we are looking at removing stack configs and support launching stacks from non-leaf environments. However, we could look having a better error message for v1.x functionality.

**Comment by theseanything** [comment]
see #249
