### ISSUE TITLE
notifications dont support resolvers

### ISSUE THREAD

**Issue by georgealton** [cloudreach/sceptre#268]
Hi guys, 

Just got round to implementing the `notifications` stack property. I had hoped to be able to use a `stack_output` resolver to get the Topic ARN so I was using a stack file which included

```yaml
notifications:
  - !stack_output env/account/monitoring/cloudformation::CloudFormationTopic

```
However the error I'm getting is 

```sh
[2017-11-22 18:38:48] - sceptre.environment - Stack environment/domain/ssl-certificate failed to launch
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sceptre/environment.py", line 252, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Library/Python/2.7/site-packages/sceptre/stack.py", line 287, in launch
    status = self.update()
  File "/Library/Python/2.7/site-packages/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/stack.py", line 247, in update
    kwargs=update_stack_kwargs
  File "/Library/Python/2.7/site-packages/sceptre/connection_manager.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/connection_manager.py", line 228, in call
    return getattr(client, command)(**kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 641, in _convert_to_request_dict
    api_params, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter NotificationARNs[0], value: <stack_output.StackOutput object at 0x10a4bd510>, type: <class 'stack_output.StackOutput'>, valid types: <type 'basestring'>
```

It seems that the notifications property can only handle strings. Could we look at enabling resolvers to be used here - especially stack output resolves, so that notifications can retrieve values from deployed stacks, and ensure dependencies are kept in check

The workaround for now is to ensure all my stacks statically include the ARN

**Comment by theseanything** [comment]
Yup, can confirm resolvers are only available for sceptre_user_data and parameters. But agree should be enabled for notifications too...
