### ISSUE TITLE
stack_output resolver gives confusing error when boto returns no 'Outputs' element

### ISSUE THREAD

**Issue by oazmon** [cloudreach/sceptre#282]
Submitting PR to fix

**Comment by theseanything** [comment]
Whats the error?

**Comment by oazmon** [comment]
The fix is to change:
           outputs = response["Stacks"][0]["Outputs"]
to:
           outputs = response["Stacks"][0]["Outputs"] \
                if "Outputs" in response["Stacks"][0] else []


The error is
Traceback (most recent call last):
  File "/Users/oazmon/git/sceptre/sceptre/environment.py", line 252, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Users/oazmon/git/sceptre/sceptre/stack.py", line 287, in launch
    status = self.update()
  File "/Users/oazmon/git/sceptre/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/oazmon/git/sceptre/sceptre/stack.py", line 234, in update
    "Parameters": self._format_parameters(self.parameters),
  File "/Users/oazmon/git/sceptre/sceptre/resolvers/__init__.py", line 72, in __get__
    return self.resolve_values(getattr(instance, self.name))
  File "/Users/oazmon/git/sceptre/sceptre/resolvers/__init__.py", line 91, in resolve_values
    attr[key] = value.resolve()
  File "/Users/oazmon/git/sceptre/sceptre/resolvers/stack_output.py", line 146, in resolve
    return self._get_output_value(dependency_stack_name, output_key)
  File "/Users/oazmon/git/sceptre/sceptre/resolvers/stack_output.py", line 35, in _get_output_value
    outputs = self._get_stack_outputs(stack_name)
  File "/Users/oazmon/git/sceptre/sceptre/resolvers/stack_output.py", line 72, in _get_stack_outputs
    outputs = response["Stacks"][0]["Outputs"]
KeyError: 'Outputs'

**Comment by theseanything** [comment]
Yup! You could probably use the `get` method for the dictionary which allows you to supply a default. 

 outputs = response["Stacks"][0].get("Outputs", [])

**Comment by ngfgrant** [comment]
Resolved in https://github.com/cloudreach/sceptre/commit/b2aa2d01d9e58e9321c24bf01dd9604a4520983c
