### ISSUE TITLE
Detect Cycles Failing with Sibling Sub-Environments

### ISSUE THREAD

**Issue by cboss24** [cloudreach/sceptre#302]
When I split an environment into two sibling  sub-environments with a dependency between them, the `launch-env` command fails when I try to launch the sub-environment. 

Reproduction steps:
```shell
$ tree
.
├── config
│   ├── bundle
│   │   ├── a
│   │   │   └── x.yaml
│   │   └── b
│   │       └── y.yaml
│   └── config.yaml
└── templates
    └── template.yaml

$ cat config/bundle/a/x.yaml
template_path: template.yaml

parameters:
  SomeInput: "Input"

$ cat config/bundle/b/y.yaml
template_path: template.yaml

parameters:
  SomeInput: !stack_output a/x::SomeOutput

$sceptre launch-env bundle/b
Traceback (most recent call last):
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/bin/sceptre", line 11, in <module>
    sys.exit(cli())
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/sceptre/cli.py", line 96, in decorated
    return func(*args, **kwargs)
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/sceptre/cli.py", line 315, in launch_env
    response = env.launch()
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/sceptre/environment.py", line 127, in launch
    self._check_for_circular_dependencies()
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/sceptre/environment.py", line 351, in _check_for_circular_dependencies
    [stack.name]
  File "/Users/cbosmann/.local/share/virtualenvs/test-wZAZWvZX/lib/python3.6/site-packages/sceptre/helpers.py", line 193, in _detect_cycles
    dependency = available_nodes[dependency_name.split("/")[-1]]
KeyError: 'x'
```

Is this expected behavior? If I remove the cycle detection this works fine.

**Comment by b-t-g** [comment]
Thanks for all of the detail/background! I think this may have come up before internally as well (I never learned the full details in that case, though); there's definitely suspicious going on when there are changes to the environment. I can try and take a look, but if you are interested in taking a look around, let me know! Sceptre, at the very least, shouldn't have a catastrophic failure because of this case.

**Comment by cboss24** [comment]
Thanks for the quick reply. So the core issue I believe is that Sceptre initializes environments only from the input path down. So if you go `launch-env bundle/b` only the `y` stack will be read in. Sceptre won't start the recursive environment load at `bundle`. The work around right now for me is to either use `external_stack_ouput` between sibling envs, or launch from the root environmenrt layer (`launch-env bundle`).

**Comment by cboss24** [comment]
Would it be possible / in the sceptre philosophy to read in stacks from the root environment downwards, but then only perform an action (launch, delete, ...) on a subset of them?

In this case, you would load in stacks `x` and `y`, but only launch `y`?

**Comment by b-t-g** [comment]
That sounds fine by me; I think it's probably the way we need to go to properly want to properly find cycles in cross-environment stacks such as your example. I was debating whether that was the right thing to do for a bit but, since you're able to deploy the stack without the cycle detection, then I see no reason why we should forbid it with its current cycle detection (since, if it weren't intended, there would be something else within Sceptre preventing the launch).

**Comment by ngfgrant** [comment]
@cboss24 I am having issues recreating this. Would it be possible to share the full output of your template and config files? There is a fix in for this and want to test it against your exact scenario.

**Comment by ngfgrant** [comment]
@cboss24 I have now been able to recreate this and identified the core part of the issue. 

I think if we are going to go down the route of loading in all stacks but only acting on `y` 
then we need to probably resolve and execute all implicit and explicit dependencies of `y`.  
For example, if `y` has `stack_output` from `x` and x does not exist then we will need to 
launch and resolve all of `x`'s dependencies too. Not such a bad thing but at some point, 
you are probably just as good doing `sceptre launch-env bundle`. 

An alternative is to add a new syntax to `!stack_output` to indicate to sceptre that you 
want to resolve a specific output from a certain environment. One suggestion for this 
could be:

`SomeInput: !stack_output bundle:a/x::SomeOutput`

I would also be interested in the use case for this so I can better understand the context
that this change would be used in.

**Comment by ngfgrant** [comment]
This is also partially related to https://github.com/cloudreach/sceptre/issues/159 too.

I think we probably need a more considered view for a v1 fix for this; even if it is a better error message, that "the stack cannot be created as it depends on another stack that doesn't exist".

Having looked into the issue a bit further I am a little concerned about changing the behaviour of `Environment.launch()`.  Happy to take others thoughts on this though.

**Comment by ngfgrant** [comment]
Closing see: https://github.com/cloudreach/sceptre/issues/422
