### ISSUE TITLE
`profile` config key is not passed to ConnectionManager

### ISSUE THREAD

**Issue by larsbutler** [cloudreach/sceptre#310]
Hi there! I was just working through my first basic Sceptre project (similar to the one [here](https://sceptre.cloudreach.com/latest/docs/get_started.html)) and I was trying a basic config file that uses the `profile` parameter to specify credentials from `~/.aws/credentials`. I ran into some issues (see below).

Here's my config.yaml:

```yaml
project_code: sample-app
region: us-east-1
profile: personal                             
template_bucket_name: lars-sample-app-conflict  # I was playing around to see if I could reproduce https://github.com/cloudreach/sceptre/issues/303
```

From what I understand of the docs, this _should_ be a valid

Before launching anything, I tried to run `sceptre status dev`. Here's what happened:

```
$ sceptre status dev
Traceback (most recent call last):
  File "/Users/larsbutler/.virtualenvs/sceptre/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre', 'console_scripts', 'sceptre')()
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/cli/helpers.py", line 39, in decorated
    return func(*args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/cli/status.py", line 25, in status_command
    write(env.describe(), output_format=output_format, no_colour=no_colour)
  File "/Users/larsbutler/proj/sceptre/sceptre/helpers.py", line 61, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/environment.py", line 104, in describe
    status = stack.get_status()
  File "/Users/larsbutler/proj/sceptre/sceptre/stack.py", line 569, in get_status
    status = self.describe()["Stacks"][0]["StackStatus"]
  File "/Users/larsbutler/proj/sceptre/sceptre/stack.py", line 328, in describe
    kwargs={"StackName": self.external_name}
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 227, in call
    client = self._get_client(service)
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 195, in _get_client
    self.clients[service] = self.boto_session.client(service)
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 160, in boto_session
    self._boto_session.get_credentials().method,
AttributeError: 'NoneType' object has no attribute 'method'
```

The error is a bit obscure and doesn't actually tell much about the real issue, but fortunately after a quick debugging session, I found out that the `profile` is not being passed to the ConnectionManager constructor. It's a fairly simple fix. Pull request coming shortly! :)

Note: A similar error happens with `sceptre launch ...`, and probably other commands.

**Comment by ngfgrant** [comment]
Thanks for the PR. This was temporarily removed when we refactored for v2. Closing as this is reimplemented as part #257
