### ISSUE TITLE
Blank Project Code - fully configurable stack name.

### ISSUE THREAD

**Issue by rmbennett** [cloudreach/sceptre#32]
If I make project_code: ""
I get :
```
An error occurred (ValidationError) when calling the UpdateStack operation: 1 validation error detected: Value '-folder-template' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
```

Which is a nicely handled error. 

However if I leave it blank (rather than an empty string "")

```
[2017-02-07 15:46:50] - sceptre.config - Reading in 'config.yaml' files...
[2017-02-07 15:46:50] - sceptre.config - Config: {'region': 'eu-west-1', 'dependencies': [], 'project_code': None}
```

Then you get a poorly handled error 

```
[2017-02-07 15:46:50] - sceptre.stack - folder/template- Hooks: {}
[2017-02-07 15:46:50] - sceptre.stack - folder/template - Updating stack
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 9, in <module>
    load_entry_point('sceptre==1.0.0', 'console_scripts', 'sceptre')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/cli.py", line 93, in decorated
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/cli.py", line 273, in update_stack
    response = env.stacks[stack].update()
  File "/Library/Python/2.7/site-packages/sceptre/helpers.py", line 79, in decorated
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/sceptre/stack.py", line 226, in update
    "StackName": self.external_name,
  File "/Library/Python/2.7/site-packages/sceptre/stack.py", line 177, in external_name
    get_external_stack_name(self.project, self.name)
  File "/Library/Python/2.7/site-packages/sceptre/helpers.py", line 183, in get_external_stack_name
    stack_name.replace("/", "-")
TypeError: sequence item 0: expected string, NoneType found
```

👍   @theseanything asked me to add this.

Can I have a fully configurable stack name? Why are there restrictions?

**Comment by ismFerDev** [comment]
@rmbennett 
You can set a StackName putting stack_name in your config/dev/file.yaml like:
template_path: templates/enis-zookeeper.json
```
stack_name: ENI
parameters:
  ManagementSecurityGroup: "xxxxxx"
  SecurityGroup: "sg-xxxxx"
  Subnets: "xxxxxx"
  Enis:  "xxxxxxx"
```
You can show the trace:
```
sceptre --var-file var/dev.yml create-stack dev eni
[2017-02-10 12:58:47] - sceptre.stack - dev/eni - Creating stack
[2017-02-10 12:58:49] - sceptre.stack - 2017-02-10T11:58:48+00:00 dev/eni ENI AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
```

**Comment by jamesroutley** [comment]
As @ismFerDev mentions, the [`stack_name`](http://sceptre.cloudreach.com/docs/stack_config.html#stack-name) property can be used to give a stack a custom name. 

The reasons for the restriction are mainly historical. Sceptre was conceived as an opinionated tool which encouraged users to follow certain 'best practices'. This included the idea of namespacing all stacks associated with a particular project. Over time, Sceptre became more un-opinionated and most of these 'best practice' requirements were loosened. I feel like we may also loosen this requirement, but I imaging this would happen as part of a version 2 release.
