### ISSUE TITLE
Can I use Structure which I can split into Functional category as below

### ISSUE THREAD

**Issue by chrisduong** [cloudreach/sceptre#347]
Hi,

I saw the suggested Structure in this doc https://sceptre.cloudreach.com/latest/docs/architecture.html

```
 - config
      - prod
          - network
              - vpc.yaml
              - subnet.yaml
          - frontend
              - api-gateway.yaml
          - application
              - lambda-get-item.yaml
              - lambda-put-item.yaml
          - database
              - dynamodb.yaml
```

When I try this layout. I've got this error.

```
❯ sceptre validate-template dev vpc
Traceback (most recent call last):
  File "/Users/cduong13/.pyenv/versions/3.5.4/bin/sceptre", line 11, in <module>
    sys.exit(cli())
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/sceptre/cli.py", line 96, in decorated
    return func(*args, **kwargs)
  File "/Users/cduong13/.pyenv/versions/3.5.4/lib/python3.5/site-packages/sceptre/cli.py", line 158, in validate_template
    response = env.stacks[stack].validate_template()
AttributeError: 'Environment' object has no attribute 'stacks'

```

**Comment by ngfgrant** [comment]
@chrisduong it looks like your command `sceptre validate-template dev vpc` is trying to look in the `dev` environment to create `vpc` stack. If these don't exist then this is likely be the cause of this problem. If you try `sceptre validate-template prod/network vpc` you might have more luck.

**Comment by chrisduong** [comment]
Yes, it works when I use Environment Name `dev/network`, not `dev`. I thought the tool will auto look up recursively under **dev folder**. Thanks
