### ISSUE TITLE
errors when launch-env

### ISSUE THREAD

**Issue by fitchxlin** [cloudreach/sceptre#360]
Hi,

With the new upgraded sceptre version Sceptre, version 1.3.4, we are getting the following error using sceptre launch-env stack_folder.  The error is below

$ winpty sceptre launch-env dev/sisense
Traceback (most recent call last):
 File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "c:\python27\lib\runpy.py", line 72, in _run_code
   exec code in run_globals
 File "C:\Python27\Scripts\sceptre.exe\__main__.py", line 9, in <module>
 File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
   return self.main(*args, **kwargs)
 File "c:\python27\lib\site-packages\click\core.py", line 696, in main
   rv = self.invoke(ctx)
 File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
   return callback(*args, **kwargs)
 File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "c:\python27\lib\site-packages\sceptre\cli.py", line 96, in decorated
   return func(*args, **kwargs)
 File "c:\python27\lib\site-packages\sceptre\cli.py", line 315, in launch_env
   response = env.launch()
 File "c:\python27\lib\site-packages\sceptre\environment.py", line 127, in launch
   self._check_for_circular_dependencies()
 File "c:\python27\lib\site-packages\sceptre\environment.py", line 351, in _check_for_circular_dependencies
   [stack.name]
 File "c:\python27\lib\site-packages\sceptre\helpers.py", line 193, in _detect_cycles
   dependency = available_nodes[dependency_name.split("/")[-1]]
KeyError: u'vpc'

**Comment by ngfgrant** [comment]
I think this is probably due to a dependency in one environment being referenced in another external environment. Suggest using `!stack_output_external` or explicitly define your dependencies as @nmyster suggested.

**Comment by ngfgrant** [comment]
Closing see: https://github.com/cloudreach/sceptre/issues/422
