### ISSUE TITLE
Can't seem to get Hooks working

### ISSUE THREAD

**Issue by bmgoau** [cloudreach/sceptre#402]
Hey Team,
I just cannot seem to get hooks working, following the example in https://sceptre.cloudreach.com/dev/docs/hooks.html
Here is my custom_hook.py:
```
from sceptre.hooks import Hook

class CustomHook(Hook):

    def __init__(self, *args, **kwargs):
        super(CustomHook, self).__init__(*args, **kwargs)

    def run(self):
        """
        run is the method called by Sceptre. It should carry out the work
        intended by this hook.

        self.argument is available from the base class and contains the
        argument defined in the Sceptre config file (see below)

        The following attributes may be available from the base class:
        self.stack_config  (A dict of data from <stack_name>.yaml)
        self.environment_config  (A dict of data from config.yaml)
        self.connection_manager (A connection_manager)
        """
        print(self.argument)
```
setup.py
```
from setuptools import setup, find_packages
setup(
    name='custom_hook',
    packages=find_packages(),
    entry_points={
        'sceptre.hooks': [
            'custom_hook = custom_hook:CustomHook',
        ],
    }
)
```
stack.yaml
```
stack_name: &stack_name {{ environment_path.0 }}-{{ environment_path.3 }}-{{environment_path.1 }}-{{ environment_path.2 }}
template_path: config/templates/{{ environment_path.0 }}-cfn.yaml
hooks:
  after_create:
    - !custom_hook 'hello'
  after_update:
    - !custom_hook 'hello'
parameters:
  ManagementInstanceType: t2.medium
  DataplaneInstanceType: t2.medium
```
When I attempt to run sceptre --debug launch-stack env stack I get:
```
$ sceptre --debug launch-stack env stack
[2018-06-14 13:45:59] - sceptre.config - Reading in 'config.yaml' files...
[2018-06-14 13:45:59] - sceptre.config - Config: {'dependencies': [], 'template_key_prefix': 'sceptre-templates', 'template_bucket_name': 'bucket', 'region': 'ap-southeast-2', 'project_code': 'project', 'iam_role': ''}
[2018-06-14 13:45:59] - sceptre.environment - Initialising stack 'env'
[2018-06-14 13:45:59] - sceptre.config - Adding resolver yaml constructors
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'project_variables.ProjectVariables'> with node tag !project_variables
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'stack_output.StackOutput'> with node tag !stack_output
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'file_contents.FileContents'> with node tag !file_contents
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'environment_variable.EnvironmentVariable'> with node tag !environment_variable
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'stack_output.StackOutputExternal'> with node tag !stack_output_external
[2018-06-14 13:45:59] - sceptre.config - Adding hook yaml constructors
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'asg_scheduled_actions.ASGScheduledActions'> with node tag !asg_scheduled_actions
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'cmd.Cmd'> with node tag !cmd
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'bash.Bash'> with node tag !bash
[2018-06-14 13:45:59] - sceptre.config - Added constructor for <class 'asg_scaling_processes.ASGScalingProcesses'> with node tag !asg_scaling_processes
[2018-06-14 13:45:59] - sceptre.config - Reading in 'gev1-stack.yaml' files...
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sceptre/cli.py", line 96, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sceptre/cli.py", line 299, in launch_stack
    response = env.stacks[stack].launch()
  File "/usr/local/lib/python2.7/site-packages/sceptre/stack.py", line 269, in launch
    self._protect_execution()
  File "/usr/local/lib/python2.7/site-packages/sceptre/stack.py", line 722, in _protect_execution
    if self.config.get("protect", False):
  File "/usr/local/lib/python2.7/site-packages/sceptre/stack.py", line 101, in config
    self.environment_config
  File "/usr/local/lib/python2.7/site-packages/sceptre/config.py", line 191, in read
    config = get_config(path)
  File "/usr/local/lib/python2.7/site-packages/sceptre/config.py", line 184, in get_config
    yaml_data = yaml.safe_load(rendered_template)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 393, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 118, in construct_sequence
    for child in node.value]
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!custom_hook'
  in "<unicode string>", line 6, column 7:
        - !custom_hook 'hello'
          ^
```
My custom hook is installed into the same python as sceptre
```
$ python
Python 2.7.15 (default, May  1 2018, 16:44:37) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import custom_hook
>>> dir(custom_hook)
['CustomHook', 'Hook', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__']
```
I'm using this version of sceptre
```
$ sceptre --version
Sceptre, version 1.3.4
```
I have tried  python setup.py install and pip install .
It looks from the debugs that sceptre isn't adding a constructor for my custom hook.
If I pull from git and use sceptre 1.3.3, then I get seemingly further in execution:
```
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sceptre/cli/helpers.py", line 39, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sceptre/cli/launch.py", line 23, in launch_command
    stack, env = get_stack_or_env(ctx, path)
  File "/usr/local/lib/python2.7/site-packages/sceptre/cli/helpers.py", line 111, in get_stack_or_env
    env = config_reader.construct_environment(path)
  File "/usr/local/lib/python2.7/site-packages/sceptre/config_reader.py", line 397, in construct_environment
    rel_path, copy.deepcopy(environment_config)
  File "/usr/local/lib/python2.7/site-packages/sceptre/config_reader.py", line 313, in _construct_stack
    config = self.read(rel_path, environment_config)
  File "/usr/local/lib/python2.7/site-packages/sceptre/config_reader.py", line 172, in read
    config.update(self._recursive_read(directory_path, filename))
  File "/usr/local/lib/python2.7/site-packages/sceptre/config_reader.py", line 202, in _recursive_read
    config.update(child_config)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by bmgoau** [comment]
Ok, I was reading the docs under /dev and https://sceptre.cloudreach.com/latest/docs/hooks.html has the correct information.

**Comment by JuanCanham** [comment]
For anybody [reading this from the future](https://xkcd.com/979/), the core issue is that the docs are referring to sceptre 2.0 which supports extensibility via python entry points.
