### ISSUE TITLE
Can't figure out how project_variables resolver works from documentation

### ISSUE THREAD

**Issue by mike-rsi** [cloudreach/sceptre#48]
I've followed the [Get Started](http://sceptre.cloudreach.com/dev/docs/get_started.html) section of the documentation, which worked well enough (ignoring the fact that it asks you to create a `.json` template when the stack config sample refers to a `.yaml` template).  On my own, I've tried to extend it a bit to use the [project_variables](http://sceptre.cloudreach.com/dev/docs/stack_config.html#project-variables) Resolver, but I can't get it to work with the way I'm interpreting the documentation.

Changes I've made to the sample code from the Get Started page:

**Created _`config/vars.yaml`_:**
```
$ touch config/vars.yaml
```
```
---
dev:
  vpc:
    CidrBlock: 10.0.0.0/16
```

**_Updated `config/dev/vpc.yaml`_:**
```
template_path: templates/vpc.yaml
parameters:
  CidrBlock: !project_variables config/vars.yaml
```
_Launching the environment:_
```
sceptre --debug launch-env dev
```

Error I'm seeing:
```
[2017-02-17 18:26:42] - sceptre.environment - Stack dev/vpc failed to launch
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sceptre\environment.py", line 244, in _manage_stack_build
    status = getattr(stack, command)()
  File "c:\python27\lib\site-packages\sceptre\helpers.py", line 79, in decorated
    return func(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\stack.py", line 273, in launch
    status = self.create()
  File "c:\python27\lib\site-packages\sceptre\hooks\__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\helpers.py", line 79, in decorated
    return func(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\stack.py", line 205, in create
    kwargs=create_stack_kwargs
  File "c:\python27\lib\site-packages\sceptre\helpers.py", line 44, in decorated
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\connection_manager.py", line 158, in call
    return getattr(client, command)(**kwargs)
  File "c:\python27\lib\site-packages\botocore\client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python27\lib\site-packages\botocore\client.py", line 513, in _make_api_call
    api_params, operation_model, context=request_context)
  File "c:\python27\lib\site-packages\botocore\client.py", line 566, in _convert_to_request_dict
    api_params, operation_model)
  File "c:\python27\lib\site-packages\botocore\validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter Parameters[0].ParameterValue, value: {'CidrBlock': '10.0.0.0/16'}, type: <type 'dict'>, valid types: <type 'basestring'>
```

It looks like the `CidrBlock` CFN parameter is being passed the full dict `{'CidrBlock': '10.0.0.0/16'}` instead of just the value `10.0.0.0/16`.  I've tried formatting the `project_variables` and the associated var file a few different ways but this is as close as I've got.   Any ideas?  Thanks!

**Comment by jamesroutley** [comment]
Hi @mike-rsi,

This is actually the intended behaviour of the `project_variables` resolver. The idea behind it is to have a file which stores a values for a single item which is used in multiple stack config files. 

I think that in your case, the value of the CIDR block is best left in `vpc.yaml`

I've read through our documentation on this and we haven't made this clear. I've opened a new [issue](https://github.com/cloudreach/sceptre/issues/49) to clarify things. 

Thanks also for pointing out the typo in the getting started guide.

Let me know if you have further questions.

**Comment by mike-rsi** [comment]
Hi @jamesroutley,

Thanks for clarifying the use of project_variables.  I think I understand how they work now. I was able to get my example to work (whether it's the best use case or not) by modifying it as follows:

_**Updated `config/vars.yaml`:**_
```
---
dev:
  vpc: 10.0.0.0/16
```

Clearer examples in the documentation would definitely help here. Thanks for creating that issue.
