### ISSUE TITLE
bad dependencies resolution in two layers configuration

### ISSUE THREAD

**Issue by arnaudgay-cr** [cloudreach/sceptre#516]
In same folder i have 3 files with dependencies:

```
cat config/common/audit/sharedservices/config-addrules.yaml 
template_path: templates/config_addrules.py
dependencies:
  - config-addrecorder
sceptre_user_data:
```

```
cat config/common/audit/sharedservices/config-addrecorder.yaml 
template_path: templates/config_addrecorder.py
dependencies:
  - config-iam-addrole
parameters:
  S3Bucket: {{environment_config.trail_bucket}}
  DeliveryFrequency: TwentyFour_Hours
  RoleARN: !stack_output config-iam-addrole::RoleArn

```

and 

```
cat config/common/audit/sharedservices/config-iam-addrole.yaml 
template_path: templates/iam_addroles.py
sceptre_user_data:
  ConfigResourcesAccess:
    DeletionPolicy: Delete
    AssumeRolePolicyDocument:
```

when I try to to execute the following command, i got an error but i was expected an explicit stack dependencies resolution.

```
sceptre launch-env common/audit/sharedservices
[2018-11-23 18:25:33] - sceptre.stack - common/audit/sharedservices/config-addrecorder - Launching stack
[2018-11-23 18:25:33] - sceptre.stack - common/audit/sharedservices/config-addrules - Launching stack
[2018-11-23 18:25:33] - sceptre.stack - common/audit/sharedservices/cloudtrail-addtrail - Launching stack
[2018-11-23 18:25:33] - sceptre.stack - common/audit/sharedservices/config-iam-addrole - Launching stack
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/cloudtrail-addtrail - Stack is in the PENDING state
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/cloudtrail-addtrail - Creating stack
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/config-addrecorder - Stack is in the PENDING state
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/config-addrules - Stack is in the PENDING state
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/config-addrecorder - Creating stack
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/config-addrules - Creating stack
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/config-iam-addrole - Stack is in the PENDING state
[2018-11-23 18:25:34] - sceptre.stack - common/audit/sharedservices/config-iam-addrole - Creating stack
[2018-11-23 18:25:34] - sceptre.environment - Stack common/audit/sharedservices/config-addrecorder failed to launch
Traceback (most recent call last):
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/environment.py", line 252, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/stack.py", line 281, in launch
    status = self.create()
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/stack.py", line 195, in create
    "Parameters": self._format_parameters(self.parameters),
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/resolvers/__init__.py", line 72, in __get__
    return self.resolve_values(getattr(instance, self.name))
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/resolvers/__init__.py", line 91, in resolve_values
    attr[key] = value.resolve()
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/resolvers/stack_output.py", line 120, in resolve
    return self._get_output_value(stack_name, self.output_key)
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/resolvers/stack_output.py", line 35, in _get_output_value
    outputs = self._get_stack_outputs(stack_name)
  File "/Users/arnaudgay/Library/Python/2.7/lib/python/site-packages/sceptre/resolvers/stack_output.py", line 68, in _get_stack_outputs
    raise StackDoesNotExistError(e.response["Error"]["Message"])
StackDoesNotExistError: Stack with id awsiac-common-audit-sharedservices-config-iam-addrole does not exist
```
 
```
sceptre --version
Sceptre, version 1.3.4
```

**Comment by ngfgrant** [comment]
Hey @arnaudgay-cr  I can see that `common/audit/sharedservices/config-addrecorder` failed to launch. Does the AWS Console give you any more information about why? Because it failed to launch the other dependencies couldn't be resolved, hence the error.

**Comment by ngfgrant** [comment]
Hey @arnaudgay-cr 

Hmm, if I recall correctly this has appeared as an issue before, it might even still be open. This issue will be resolved in version 2, however.

Sorry can't be more help right now - main effort is to get v2 released.

**Comment by arnaudgay-cr** [comment]
Ok thx let us try on V2 and let you know.

**Comment by ngfgrant** [comment]
That would be great, the migration guide is here: https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2

**Comment by ngfgrant** [comment]
Closing for now as this should be resolved in v2. Feel free to open if you run in to this issue again in v2.
