### ISSUE TITLE
launch --ignore-dependencies with stack output resolver error

### ISSUE THREAD

**Issue by jmwyson** [cloudreach/sceptre#545]
Hi,

I have the following stack config structure:

config/env/s1.yaml

```
template_path: mystack.template.yaml
parameters:
  Name: s1
  Value: s1
```

config/env/s2.yaml

```
template_path: mystack.template.yaml
dependencies:
  - env/s1.yaml
parameters:
  Name: s2
  Value: s2
```

config/env/s3.yaml

```
template_path: mystack.template.yaml
parameters:
  Name: s3
  Value: !stack_output env/s2.yaml::OutputValue
```

I run the stacks manually in order using these commands:
`sceptre --ignore-dependencies launch env/s1.yaml`
`sceptre --ignore-dependencies launch env/s2.yaml`
`sceptre --ignore-dependencies launch env/s3.yaml`

s1 and s2 complete but s3 fails with this error:

```
$ sceptre --ignore-dependencies launch env/s3.yaml
Do you want to launch 'env/s3.yaml' [y/N]: y
[2018-12-08 09:56:18] - env/s3 - Launching Stack
[2018-12-08 09:56:21] - env/s3 - Stack is in the PENDING state
[2018-12-08 09:56:21] - env/s3 - Creating Stack
Traceback (most recent call last):
File "/usr/bin/sceptre", line 11, in
sys.exit(cli())
File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/lib/python2.7/site-packages/sceptre/cli/helpers.py", line 37, in decorated
return func(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/sceptre/cli/launch.py", line 39, in launch_command
responses = plan.launch()
File "/usr/lib/python2.7/site-packages/sceptre/plan/plan.py", line 121, in launch
return self._execute(*args)
File "/usr/lib/python2.7/site-packages/sceptre/plan/plan.py", line 37, in _execute
return executor.execute(*args)
File "/usr/lib/python2.7/site-packages/sceptre/plan/executor.py", line 55, in execute
stack, status = future.result()
File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
return self.__get_result()
File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/sceptre/plan/executor.py", line 62, in _execute
result = getattr(actions, self.command)(*args)
File "/usr/lib/python2.7/site-packages/sceptre/plan/actions.py", line 184, in launch
status = self.create()
File "/usr/lib/python2.7/site-packages/sceptre/hooks/__init__.py", line 104, in decorated
response = func(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/sceptre/plan/actions.py", line 60, in create
"Parameters": self._format_parameters(self.stack.parameters),
File "/usr/lib/python2.7/site-packages/sceptre/resolvers/__init__.py", line 75, in __get__
resolve, getattr(instance, self.name), Resolver
File "/usr/lib/python2.7/site-packages/sceptre/helpers.py", line 60, in _call_func_on_values
func_on_instance(key)
File "/usr/lib/python2.7/site-packages/sceptre/helpers.py", line 54, in func_on_instance
func(attr, key, value)
File "/usr/lib/python2.7/site-packages/sceptre/resolvers/__init__.py", line 71, in resolve
attr[key] = value.resolve()
File "/usr/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 133, in resolve
stack for stack in self.stack.dependencies if stack.name == friendly_stack_name
StopIteration
--
```

When I use below command to launch the entire env, all stacks launch successfully and the error does not appear:
`sceptre launch env`

I also tried using below command to launch s3. This completes successfully too but also launches the other two stacks as expected:
`sceptre launch env/s3.yaml`

I was wondering if there is a way to launch stack s3 on its own in sceptre v2. This setup worked in sceptre v1 and stack s3 can be launched on its own with the launch-stack command.

**Comment by ngfgrant** [comment]
Hi @jmwyson 

A couple of questions - looking at the config for s3 should the output on the `stack_output` be like the below?:

```yaml
Value: !stack_output env/s2.yaml::Value
```

Also, could you try using a external_stack_output_resolver to see if that solves the issue:

```yaml
Value: !stack_output_external <your-project-code>-env-s2::Value
```

The issue with `env/s3.yaml` is that it is using a Stack Output resolver, Sceptre will add the stack you are referencing as a dependency but obviously we are wanting to ignore-dependencies in this case. So it is unlikely that value will ever resolve. I think using stack_output_external will get around that as Sceptre will just go an get that value from AWS, rather than trying to resolve the dependency. 

If the `external_stack_output` solves this for you then I will make a note in the documentation regarding this and I think better error reporting would also help.

**Comment by jmwyson** [comment]
Hi @ngfgrant 

You are  correct that what I meant for the `stack_output` is getting the value of stack s2.

I tested your recommendation and using `!stack_output_external` allows `sceptre --ignore-dependencies launch`  to continue. 

To summarize, to launch a single stack dependent on another stack without affecting the other stacks, we would need to change all !stack_output to !stack_output_external.

Thank you.

**Comment by ngfgrant** [comment]
Hi @jmwyson glad to hear that you are able to proceed. 

The `launch` command will either update or create a resource. Of course, if you have a `stack_output` that isn't affected by the changes the launch command then there shouldn't be any downside to just launching as normal without `--ignore-dependencies`. Using `stack_output_external` and `--ignore-dependencies` won't guarantee success. The dependency will need to be resolved in order, hence the default behaviour.

I am going to close for now.
