### ISSUE TITLE
sceptre list output envvar format broken

### ISSUE THREAD

**Issue by m1keil** [cloudreach/sceptre#576]
See the output:

    $ sceptre --version
    Sceptre, version 2.0.1

    $ sceptre list outputs dev/us-east-1/bucket
    - dev/us-east-1/bucket:
    - Description: Created S3 bucket ARN
        OutputKey: S3BucketARN
        OutputValue: arn:aws:s3:::RETRACTED
    - Description: Created S3 bucket name
        OutputKey: S3BucketName
        OutputValue: RETRACTED

    $ sceptre list outputs dev/us-east-1/bucket -e envvar
    if not isinstance(key, collections.Hashable):
    Traceback (most recent call last):
    File "/Users/msverdlik/.virtualenvs/prj/bin/sceptre", line 11, in <module>
        sys.exit(cli())
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
    File "/Users/msverdlik/.virtualenvs/prj/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
    File "/Users/msverdlik/.virtualenvs/prd/lib/python3.7/site-packages/sceptre/cli/helpers.py", line 37, in decorated
        return func(*args, **kwargs)

**Comment by ngfgrant** [comment]
I have resolved this in branch `fix-envvar-output`. Will get it released in 2.0.2
