### ISSUE TITLE
Improve exception handling for KeyErrors

### ISSUE THREAD

**Issue by ngfgrant** [cloudreach/sceptre#623]
# CONTEXT

If a required key is missing from a stack or config file and Sceptre attempts to load the config or stack the user is presented with a KeyError.

```python
Traceback (most recent call last):
  File "/Users/niallgrant/.pyenv/versions/sceptre-3.6.2/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre', 'console_scripts', 'sceptre')()
  File "/Users/niallgrant/.pyenv/versions/3.6.2/envs/sceptre-3.6.2/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niallgrant/.pyenv/versions/3.6.2/envs/sceptre-3.6.2/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/niallgrant/.pyenv/versions/3.6.2/envs/sceptre-3.6.2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niallgrant/.pyenv/versions/3.6.2/envs/sceptre-3.6.2/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niallgrant/.pyenv/versions/3.6.2/envs/sceptre-3.6.2/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/niallgrant/.pyenv/versions/3.6.2/envs/sceptre-3.6.2/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/niallgrant/Codebase/sceptre/sceptre/sceptre/cli/helpers.py", line 37, in decorated
    return func(*args, **kwargs)
  File "/Users/niallgrant/Codebase/sceptre/sceptre/sceptre/cli/template.py", line 66, in generate_command
    plan = SceptrePlan(context)
  File "/Users/niallgrant/Codebase/sceptre/sceptre/sceptre/plan/plan.py", line 31, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/Users/niallgrant/Codebase/sceptre/sceptre/sceptre/config/reader.py", line 203, in construct_stacks
    stack = self._construct_stack(rel_path, stack_group_config)
  File "/Users/niallgrant/Codebase/sceptre/sceptre/sceptre/config/reader.py", line 429, in _construct_stack
    config["template_path"]
KeyError: 'template_path'
```

Required keys are detailed in the dicts: https://github.com/cloudreach/sceptre/blob/master/sceptre/config/reader.py#L54

and 

https://github.com/cloudreach/sceptre/blob/master/sceptre/config/reader.py#L66

# DONE WHEN

Instead of a KeyError the user should see a nice error message saying they need to include the required field. Bonus points for saying which stack failed/which file they need to amend.

**Comment by devenney** [comment]
I've been playing around with this to determine the best solution - ideally one which will adapt to the addition/removal of mandatory keys. However I've got a few questions:

1. Is it intentional that all configuration (that is, both stack and stack group config) can be stored in a single file? I had been differentiating these in my error messages such that the user knew which type of configuration file was missing an attribute but the code doesn't seem as opinionated as the documentation.
2. Obviously in testing my fix I've been mangling key names. Do we want an issue to warn the user when one of their config files includes an unknown key (e.g. `porject_code`)? If so, do we just want to roll it into this one?
